/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.rummypresentacion.vista;

import itson.rummypresentacion.modelo.IModelo;
import itson.rummypresentacion.modelo.IObserver;

/**
 *
 * @author Dana Chavez
 */
public class UI_ConfigurarPartida extends javax.swing.JFrame implements IObserver {

    /**
     * Creates new form ConfigurarPartida
     */
    public UI_ConfigurarPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 743));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("SIGUIENTE");
        jButton1.setActionCommand("jButtonSiguiente");
        jButton1.setMaximumSize(new java.awt.Dimension(242, 55));
        jButton1.setMinimumSize(new java.awt.Dimension(242, 55));
        jButton1.setPreferredSize(new java.awt.Dimension(242, 55));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, -1, -1));

        jButtonRegresar.setText("REGRESAR");
        jButtonRegresar.setMaximumSize(new java.awt.Dimension(242, 55));
        jButtonRegresar.setMinimumSize(new java.awt.Dimension(242, 55));
        jButtonRegresar.setPreferredSize(new java.awt.Dimension(242, 55));
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurarPartida.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    @Override
    public void update(IModelo modelo) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
